# Name of your application. Used to uniquely configure containers.
service: bizteacher

# Name of the container image.
image: biz/portal
# ssh:
#   user: lighthouse ### yeah

# Deploy to these servers.
servers:
  web:
    options:
      network:
        - asgard
    directories:
      - storage:/rails/storage
    hosts:
      - 150.158.27.74
    labels:
      traefik.http.routers.bizteacher-web.rule: Host(`bizteacher.top`)
      traefik.http.routers.bizteacher-web.entrypoints: websecure
      traefik.http.routers.bizteacher-web.tls.certresolver: letsencrypt
      # traefik.http.routers.registry-badboy.rule: Host(`repos.bizteacher.top`)
      # traefik.http.routers.registry-badboy.entrypoints: websecure
      # traefik.http.routers.registry-badboy.tls.certresolver: letsencrypt


# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  server: repos.bizteacher.top
  username: fang
  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  secret:
    - RAILS_MASTER_KEY
    - KAMAL_REGISTRY_PASSWORD
    - REDIS_URL


#   clear:
#     DB_HOST: 192.168.0.2

# Use a different ssh user than root

# Configure builder setup.
builder:
#   remote:
#     arch: amd64
#     host: ssh://root@192.168.10.109
  multiarch: false
#   args:
#     RUBY_VERSION: 3.2.0
#   secrets:
#     - GITHUB_TOKEN

# Use accessory services (secrets come from .env).
# accessories:
#   db:
#     image: mysql:8.0
#     host: 192.168.0.2
#     port: 3306
#     env:
#       clear:
#         MYSQL_ROOT_HOST: '%'
#       secret:
#         - MYSQL_ROOT_PASSWORD
#     files:
#       - config/mysql/production.cnf:/etc/mysql/my.cnf
#       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
#     directories:
#       - data:/var/lib/mysql
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data

# Configure custom arguments for Traefik
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  max_attempts: 10
  interval: 3s
#   path: /healthz
#   port: 4000

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
# asset_path: /rails/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2
# traefik:
#   # host_port: 8080
#   labels:
#     traefik.http.routers.registry-reg2.rule: Host(`repos.bizteacher.top`)
#     traefik.http.routers.registry-reg2.tls: true
#     traefik.http.routers.registry-reg2.tls.certresolver: letsencrypt
#     traefik.http.routers.registry-reg2.tls.domains[0].main: "repos.bizteacher.top"
#     traefik.http.routers.registry-reg2.tls.domains[0].sans: "*.bizteacher.top"
traefik:
  env:
    secret:
      - TENCENTCLOUD_SECRET_ID
      - TENCENTCLOUD_SECRET_KEY

  labels:
    traefik.enable: true
    traefik.http.routers.dashboard.rule: Host(`api.bizteacher.top`)
    traefik.http.routers.dashboard.service: api@internal
    traefik.http.routers.dashboard.middlewares: auth
    traefik.http.middlewares.auth.basicauth.users: fang:$2y$05$H2o72tMaO.TwY1wNQUV1K.fhjRgLHRDWohFvUZOJHBEtUXNKrqUKi # test:password
  options:
    network:
      - asgard
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    api: true
    api.dashboard: true
    api.debug: true
    #
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    # entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    # entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls: true
    entrypoints.websecure.http.tls.domains[0].main: "bizteacher.top"
    entrypoints.websecure.http.tls.domains[0].sans: "*.bizteacher.top"
    # entrypoints.websecure.http.tls.domains[1].main: "repos.bizteacher.top"
    # entrypoints.websecure.http.tls.domains[1].sans: "*.bizteacher.top"
    # entrypoints.websecure.http.tls.domains[2].main: "api.bizteacher.top"
    # entrypoints.websecure.http.tls.domains[2].sans: "*.bizteacher.top"
    certificatesResolvers.letsencrypt.acme.email: "29148452@qq.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesresolvers.letsencrypt.acme.dnschallenge.provider: tencentcloud
    # certificatesResolvers.letsencrypt.acme.httpchallenge: true
    # certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
